apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    user: ${TIMESCALE_USER}
    secureJsonData:
      password: ${TIMESCALE_PASSWORD}
    jsonData:
      database: smartgrid
      sslmode: disable
      timescaledb: true
    isDefault: true

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
